version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "strapi-synchronizer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-654kvsuiw6rp"
s3_prefix = "community-synchronizer"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
