name: Python application
on:
  push:
    branches:
      - main
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    environment: production
    env:
      MONGODB_CONNECTION: ${{ secrets.MONGODB_CONNECTION }}
      GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
      STRAPI_API_KEY: ${{ secrets.STRAPI_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      # Build using SAM
      - run: sam build --use-container
      # Deploy on AWS
      - run: sam deploy
